INSERT INTO security_groups (group_name) VALUES('Sõbrad');
INSERT INTO security_groups (group_name) VALUES('Perekond');
INSERT INTO security_groups (group_name) VALUES('Administraator');

INSERT INTO recipe_ethnicity (ethnic_desc) VALUES ('Itaalia');
INSERT INTO recipe_ethnicity (ethnic_desc) VALUES ('Hiina');
INSERT INTO recipe_ethnicity (ethnic_desc) VALUES ('Jaapani');
INSERT INTO recipe_ethnicity (ethnic_desc) VALUES ('Mehhiko');
INSERT INTO recipe_ethnicity (ethnic_desc) VALUES ('Ameerika');
INSERT INTO recipe_ethnicity (ethnic_desc) VALUES ('Austraalia');
INSERT INTO recipe_ethnicity (ethnic_desc) VALUES ('Hispaania');
INSERT INTO recipe_ethnicity (ethnic_desc) VALUES ('Aasia');
INSERT INTO recipe_ethnicity (ethnic_desc) VALUES ('Prantsuse');
INSERT INTO recipe_ethnicity (ethnic_desc) VALUES ('Skandinaavia');
INSERT INTO recipe_ethnicity (ethnic_desc) VALUES ('Eesti');
INSERT INTO recipe_ethnicity (ethnic_desc) VALUES ('Aafrika');
INSERT INTO recipe_ethnicity (ethnic_desc) VALUES ('Vene');

INSERT INTO recipe_units (unit_id,unit_desc,unit_abbr) VALUES ('1','Tükk(i)','tk');
INSERT INTO recipe_units (unit_id,unit_desc,unit_abbr) VALUES ('2','Viil(u)','viil');
INSERT INTO recipe_units (unit_id,unit_desc,unit_abbr) VALUES ('3','Küün(i)','küün');
INSERT INTO recipe_units (unit_id,unit_desc,unit_abbr) VALUES ('4','briis','br');
INSERT INTO recipe_units (unit_id,unit_desc,unit_abbr) VALUES ('5','Pakk(i)','pk');
INSERT INTO recipe_units (unit_id,unit_desc,unit_abbr) VALUES ('6','Tops(i)','tps');
INSERT INTO recipe_units (unit_id,unit_desc,unit_abbr) VALUES ('7','Tilk(a)','tr');
INSERT INTO recipe_units (unit_id,unit_desc,unit_abbr) VALUES ('8','Kimp(u)','kmp');
INSERT INTO recipe_units (unit_id,unit_desc,unit_abbr) VALUES ('9','Spritzer','spr');
INSERT INTO recipe_units (unit_id,unit_desc,unit_abbr) VALUES ('10','Kartong','kat');
INSERT INTO recipe_units (unit_id,unit_desc,unit_abbr) VALUES ('11','Tass(i)','ta');
INSERT INTO recipe_units (unit_id,unit_desc,unit_abbr) VALUES ('12','Suplusika(s)(t)_imp','sl');
INSERT INTO recipe_units (unit_id,unit_desc,unit_abbr) VALUES ('13','Teelusika(s)(t)_imp','tl');
INSERT INTO recipe_units (unit_id,unit_desc,unit_abbr) VALUES (14,'Nael','lb');
INSERT INTO recipe_units (unit_id,unit_desc,unit_abbr) VALUES (15,'Unts','oz');
INSERT INTO recipe_units (unit_id,unit_desc,unit_abbr) VALUES (16,'Pint','pt');
INSERT INTO recipe_units (unit_id,unit_desc,unit_abbr) VALUES (17,'Quart','q');
INSERT INTO recipe_units (unit_id,unit_desc,unit_abbr) VALUES (18,'Gallon','gal');
INSERT INTO recipe_units (unit_id,unit_desc,unit_abbr) VALUES (19,'Milligramm','mg');
INSERT INTO recipe_units (unit_id,unit_desc,unit_abbr) VALUES (20,'Centigramm','cg');
INSERT INTO recipe_units (unit_id,unit_desc,unit_abbr) VALUES (21,'Gramm','g');
INSERT INTO recipe_units (unit_id,unit_desc,unit_abbr) VALUES (22,'Kilogramm','kg');
INSERT INTO recipe_units (unit_id,unit_desc,unit_abbr) VALUES (23,'Milliliiter','ml');
INSERT INTO recipe_units (unit_id,unit_desc,unit_abbr) VALUES (24,'Centiliiter','cl');
INSERT INTO recipe_units (unit_id,unit_desc,unit_abbr) VALUES (25,'Liiter','l');
INSERT INTO recipe_units (unit_id,unit_desc,unit_abbr) VALUES (26,'Deciliiter','dl');
INSERT INTO recipe_units (unit_id,unit_desc,unit_abbr) VALUES (27,'Suplusika(s)(t)_m','sl');
INSERT INTO recipe_units (unit_id,unit_desc,unit_abbr) VALUES (28,'Teelusika(s)(t)_m','tl');

INSERT INTO recipe_locations (location_desc) VALUES ('Alkohol');
INSERT INTO recipe_locations (location_desc) VALUES ('Bioloogiline');
INSERT INTO recipe_locations (location_desc) VALUES ('Oad');
INSERT INTO recipe_locations (location_desc) VALUES ('Kommid');
INSERT INTO recipe_locations (location_desc) VALUES ('Leib');
INSERT INTO recipe_locations (location_desc) VALUES ('Liha ja kalakonservid');
INSERT INTO recipe_locations (location_desc) VALUES ('Konserveeritud puu ja köögiviljad');
INSERT INTO recipe_locations (location_desc) VALUES ('Kohvi, Tee &amp; Kakao');
INSERT INTO recipe_locations (location_desc) VALUES ('Maitseained');
INSERT INTO recipe_locations (location_desc) VALUES ('Küpsised');
INSERT INTO recipe_locations (location_desc) VALUES ('plaksukommid');
INSERT INTO recipe_locations (location_desc) VALUES ('Dairy');
INSERT INTO recipe_locations (location_desc) VALUES ('Deli');
INSERT INTO recipe_locations (location_desc) VALUES ('Drink mix');
INSERT INTO recipe_locations (location_desc) VALUES ('Facial Tissue');
INSERT INTO recipe_locations (location_desc) VALUES ('Food Storage');
INSERT INTO recipe_locations (location_desc) VALUES ('Free');
INSERT INTO recipe_locations (location_desc) VALUES ('Frozen Foods');
INSERT INTO recipe_locations (location_desc) VALUES ('HABA');
INSERT INTO recipe_locations (location_desc) VALUES ('Hand Soap');
INSERT INTO recipe_locations (location_desc) VALUES ('Hot &amp; Cold Cereal');
INSERT INTO recipe_locations (location_desc) VALUES ('Household Cleaners');
INSERT INTO recipe_locations (location_desc) VALUES ('Juice &amp; Cocktail');
INSERT INTO recipe_locations (location_desc) VALUES ('Kosher/Ethnic');
INSERT INTO recipe_locations (location_desc) VALUES ('Laundry Detergents');
INSERT INTO recipe_locations (location_desc) VALUES ('Meat');
INSERT INTO recipe_locations (location_desc) VALUES ('Naturaalne &amp; Orgaaniline');
INSERT INTO recipe_locations (location_desc) VALUES ('Õli/Äädikas/Salatikastmed');
INSERT INTO recipe_locations (location_desc) VALUES ('Pannkoogid &amp; Siirup');
INSERT INTO recipe_locations (location_desc) VALUES ('Paper Serving Ware');
INSERT INTO recipe_locations (location_desc) VALUES ('Pasta &amp; Soust');
INSERT INTO recipe_locations (location_desc) VALUES ('Pähklivõi/Tarretis/Mesi');
INSERT INTO recipe_locations (location_desc) VALUES ('Produce');
INSERT INTO recipe_locations (location_desc) VALUES ('Riis');

INSERT INTO recipe_bases (base_desc) VALUES ('Loom');
INSERT INTO recipe_bases (base_desc) VALUES ('Leib/sai');
INSERT INTO recipe_bases (base_desc) VALUES ('Muna');
INSERT INTO recipe_bases (base_desc) VALUES ('Puuvili');
INSERT INTO recipe_bases (base_desc) VALUES ('Teravili');
INSERT INTO recipe_bases (base_desc) VALUES ('Lammas');
INSERT INTO recipe_bases (base_desc) VALUES ('Muu');
INSERT INTO recipe_bases (base_desc) VALUES ('Pasta');
INSERT INTO recipe_bases (base_desc) VALUES ('Siga');
INSERT INTO recipe_bases (base_desc) VALUES ('Kodulind');
INSERT INTO recipe_bases (base_desc) VALUES ('Meretoit');
INSERT INTO recipe_bases (base_desc) VALUES ('Taimetoit');

INSERT INTO recipe_prep_time (time_desc) VALUES ('0 Min');
INSERT INTO recipe_prep_time (time_desc) VALUES ('1-10 Min');
INSERT INTO recipe_prep_time (time_desc) VALUES ('10-30 Min');
INSERT INTO recipe_prep_time (time_desc) VALUES ('30-60 Min');
INSERT INTO recipe_prep_time (time_desc) VALUES ('60+ Min');

INSERT INTO recipe_difficulty (difficult_desc) VALUES ('Kerge');
INSERT INTO recipe_difficulty (difficult_desc) VALUES ('Keskmine');
INSERT INTO recipe_difficulty (difficult_desc) VALUES ('Raske');
INSERT INTO recipe_difficulty (difficult_desc) VALUES ('Ekspert');

INSERT INTO recipe_courses (course_desc) VALUES ('Hommikusöök');
INSERT INTO recipe_courses (course_desc) VALUES ('Suupiste');
INSERT INTO recipe_courses (course_desc) VALUES ('Lõuna');
INSERT INTO recipe_courses (course_desc) VALUES ('Eelroog');
INSERT INTO recipe_courses (course_desc) VALUES ('Kõrvalroog');
INSERT INTO recipe_courses (course_desc) VALUES ('Pearoog');
INSERT INTO recipe_courses (course_desc) VALUES ('Dessert');
INSERT INTO recipe_courses (course_desc) VALUES ('Joogid');

