INSERT INTO security_groups (group_name) VALUES('Friends');
INSERT INTO security_groups (group_name) VALUES('Family');
INSERT INTO security_groups (group_name) VALUES('Maintainers');

INSERT INTO recipe_ethnicity (ethnic_desc) VALUES ('American');
INSERT INTO recipe_ethnicity (ethnic_desc) VALUES ('Chinese');
INSERT INTO recipe_ethnicity (ethnic_desc) VALUES ('German');
INSERT INTO recipe_ethnicity (ethnic_desc) VALUES ('Greek');
INSERT INTO recipe_ethnicity (ethnic_desc) VALUES ('Italian');
INSERT INTO recipe_ethnicity (ethnic_desc) VALUES ('Japanese');
INSERT INTO recipe_ethnicity (ethnic_desc) VALUES ('Mexican');
INSERT INTO recipe_ethnicity (ethnic_desc) VALUES ('Middle Eastern');
INSERT INTO recipe_ethnicity (ethnic_desc) VALUES ('None');
INSERT INTO recipe_ethnicity (ethnic_desc) VALUES ('Slavic');

INSERT INTO recipe_units (unit_id,unit_desc,unit_abbr) VALUES (1,'Unit','ea');
INSERT INTO recipe_units (unit_id,unit_desc,unit_abbr) VALUES (2,'Slice','sli');
INSERT INTO recipe_units (unit_id,unit_desc,unit_abbr) VALUES (3,'Clove','clv');
INSERT INTO recipe_units (unit_id,unit_desc,unit_abbr) VALUES (4,'Pinch','pn');
INSERT INTO recipe_units (unit_id,unit_desc,unit_abbr) VALUES (5,'Package','pk');
INSERT INTO recipe_units (unit_id,unit_desc,unit_abbr) VALUES (6,'Can','cn');
INSERT INTO recipe_units (unit_id,unit_desc,unit_abbr) VALUES (7,'Drop','dr');
INSERT INTO recipe_units (unit_id,unit_desc,unit_abbr) VALUES (8,'Bunch','bn');
INSERT INTO recipe_units (unit_id,unit_desc,unit_abbr) VALUES (9,'Dash','ds');
INSERT INTO recipe_units (unit_id,unit_desc,unit_abbr) VALUES (10,'Carton','ct');
INSERT INTO recipe_units (unit_id,unit_desc,unit_abbr) VALUES (11,'Cup','c');
INSERT INTO recipe_units (unit_id,unit_desc,unit_abbr) VALUES (12,'Tablespoon','T');
INSERT INTO recipe_units (unit_id,unit_desc,unit_abbr) VALUES (13,'Teaspoon','t');
INSERT INTO recipe_units (unit_id,unit_desc,unit_abbr) VALUES (14,'Pound','lb');
INSERT INTO recipe_units (unit_id,unit_desc,unit_abbr) VALUES (15,'Ounce','oz');
INSERT INTO recipe_units (unit_id,unit_desc,unit_abbr) VALUES (16,'Pint','pt');
INSERT INTO recipe_units (unit_id,unit_desc,unit_abbr) VALUES (17,'Quart','q');
INSERT INTO recipe_units (unit_id,unit_desc,unit_abbr) VALUES (18,'Gallon','gal');
INSERT INTO recipe_units (unit_id,unit_desc,unit_abbr) VALUES (19,'Milligram','mg');
INSERT INTO recipe_units (unit_id,unit_desc,unit_abbr) VALUES (20,'Centigram','cg');
INSERT INTO recipe_units (unit_id,unit_desc,unit_abbr) VALUES (21,'Gram','g');
INSERT INTO recipe_units (unit_id,unit_desc,unit_abbr) VALUES (22,'Kilogram','kg');
INSERT INTO recipe_units (unit_id,unit_desc,unit_abbr) VALUES (23,'Milliliter','ml');
INSERT INTO recipe_units (unit_id,unit_desc,unit_abbr) VALUES (24,'Centiliter','cl');
INSERT INTO recipe_units (unit_id,unit_desc,unit_abbr) VALUES (25,'Liter','l');
INSERT INTO recipe_units (unit_id,unit_desc,unit_abbr) VALUES (26,'Deciliter','dl');
INSERT INTO recipe_units (unit_id,unit_desc,unit_abbr) VALUES (27,'Tablespoon_m','tbsp');
INSERT INTO recipe_units (unit_id,unit_desc,unit_abbr) VALUES (28,'Teaspoon_m','tsp');


INSERT INTO recipe_locations (location_desc) VALUES ('Alcohol');
INSERT INTO recipe_locations (location_desc) VALUES ('Bakery');
INSERT INTO recipe_locations (location_desc) VALUES ('Baking needs');
INSERT INTO recipe_locations (location_desc) VALUES ('Beans');
INSERT INTO recipe_locations (location_desc) VALUES ('Bread');
INSERT INTO recipe_locations (location_desc) VALUES ('Breakfast bars');
INSERT INTO recipe_locations (location_desc) VALUES ('Candy');
INSERT INTO recipe_locations (location_desc) VALUES ('Canned Fruit');
INSERT INTO recipe_locations (location_desc) VALUES ('Canned Meat &amp; Fish');
INSERT INTO recipe_locations (location_desc) VALUES ('Canned Vegetables');
INSERT INTO recipe_locations (location_desc) VALUES ('Coffee, Tea &amp; Cocoa');
INSERT INTO recipe_locations (location_desc) VALUES ('Condiments');
INSERT INTO recipe_locations (location_desc) VALUES ('Cookies');
INSERT INTO recipe_locations (location_desc) VALUES ('Crackers');
INSERT INTO recipe_locations (location_desc) VALUES ('Dairy');
INSERT INTO recipe_locations (location_desc) VALUES ('Deli');
INSERT INTO recipe_locations (location_desc) VALUES ('Drink mix');
INSERT INTO recipe_locations (location_desc) VALUES ('Facial Tissue');
INSERT INTO recipe_locations (location_desc) VALUES ('Food Storage');
INSERT INTO recipe_locations (location_desc) VALUES ('Free');
INSERT INTO recipe_locations (location_desc) VALUES ('Frozen Foods');
INSERT INTO recipe_locations (location_desc) VALUES ('HABA');
INSERT INTO recipe_locations (location_desc) VALUES ('Hand Soap');
INSERT INTO recipe_locations (location_desc) VALUES ('Hot &amp; Cold Cereal');
INSERT INTO recipe_locations (location_desc) VALUES ('Household Cleaners');
INSERT INTO recipe_locations (location_desc) VALUES ('Juice &amp; Cocktail');
INSERT INTO recipe_locations (location_desc) VALUES ('Kosher/Ethnic');
INSERT INTO recipe_locations (location_desc) VALUES ('Laundry Detergents');
INSERT INTO recipe_locations (location_desc) VALUES ('Meat');
INSERT INTO recipe_locations (location_desc) VALUES ('Natural &amp; Organic');
INSERT INTO recipe_locations (location_desc) VALUES ('Oil/Vinegar/Dressings');
INSERT INTO recipe_locations (location_desc) VALUES ('Pancakes &amp; Syrup');
INSERT INTO recipe_locations (location_desc) VALUES ('Paper Serving Ware');
INSERT INTO recipe_locations (location_desc) VALUES ('Pasta &amp; Sauce');
INSERT INTO recipe_locations (location_desc) VALUES ('Peanut Butter/Jelly/Honey');
INSERT INTO recipe_locations (location_desc) VALUES ('Produce');
INSERT INTO recipe_locations (location_desc) VALUES ('Rice');
INSERT INTO recipe_locations (location_desc) VALUES ('Salty Snacks &amp; Chips');
INSERT INTO recipe_locations (location_desc) VALUES ('Seafood');
INSERT INTO recipe_locations (location_desc) VALUES ('Soda pop');
INSERT INTO recipe_locations (location_desc) VALUES ('Soup');
INSERT INTO recipe_locations (location_desc) VALUES ('Spices');
INSERT INTO recipe_locations (location_desc) VALUES ('Toilet Paper');

INSERT INTO recipe_bases (base_desc) VALUES ('Beef');
INSERT INTO recipe_bases (base_desc) VALUES ('Bread');
INSERT INTO recipe_bases (base_desc) VALUES ('Egg');
INSERT INTO recipe_bases (base_desc) VALUES ('Fruit');
INSERT INTO recipe_bases (base_desc) VALUES ('Grain');
INSERT INTO recipe_bases (base_desc) VALUES ('Lamb');
INSERT INTO recipe_bases (base_desc) VALUES ('Other');
INSERT INTO recipe_bases (base_desc) VALUES ('Pasta');
INSERT INTO recipe_bases (base_desc) VALUES ('Pork/Ham');
INSERT INTO recipe_bases (base_desc) VALUES ('Poultry');
INSERT INTO recipe_bases (base_desc) VALUES ('Seafood');
INSERT INTO recipe_bases (base_desc) VALUES ('Vegetable');

INSERT INTO recipe_prep_time (time_desc) VALUES ('0 Minutes');
INSERT INTO recipe_prep_time (time_desc) VALUES ('1-10 Minutes');
INSERT INTO recipe_prep_time (time_desc) VALUES ('10-30 Minutes');
INSERT INTO recipe_prep_time (time_desc) VALUES ('30-60 Minutes');
INSERT INTO recipe_prep_time (time_desc) VALUES ('60+ Minutes');

INSERT INTO recipe_difficulty (difficult_desc) VALUES ('Easy');
INSERT INTO recipe_difficulty (difficult_desc) VALUES ('Intermediate');
INSERT INTO recipe_difficulty (difficult_desc) VALUES ('Difficult');
INSERT INTO recipe_difficulty (difficult_desc) VALUES ('Expert');

INSERT INTO recipe_courses (course_desc) VALUES ('Breakfast');
INSERT INTO recipe_courses (course_desc) VALUES ('Snack');
INSERT INTO recipe_courses (course_desc) VALUES ('Lunch');
INSERT INTO recipe_courses (course_desc) VALUES ('Appetizer');
INSERT INTO recipe_courses (course_desc) VALUES ('Side Dish');
INSERT INTO recipe_courses (course_desc) VALUES ('Entree');
INSERT INTO recipe_courses (course_desc) VALUES ('Dessert');
INSERT INTO recipe_courses (course_desc) VALUES ('Beverage');

INSERT INTO recipe_meals (meal_name) VALUES ('Breakfast');
INSERT INTO recipe_meals (meal_name) VALUES ('Brunch');
INSERT INTO recipe_meals (meal_name) VALUES ('Lunch');
INSERT INTO recipe_meals (meal_name) VALUES ('Afternoon Snack');
INSERT INTO recipe_meals (meal_name) VALUES ('Dinner');
INSERT INTO recipe_meals (meal_name) VALUES ('Dessert');

INSERT INTO recipe_prices (price_desc) VALUES ('$0-$10');
INSERT INTO recipe_prices (price_desc) VALUES ('$10-$15');
INSERT INTO recipe_prices (price_desc) VALUES ('$15-$20');
INSERT INTO recipe_prices (price_desc) VALUES ('$20-$25');
INSERT INTO recipe_prices (price_desc) VALUES ('$25-$30');
INSERT INTO recipe_prices (price_desc) VALUES ('$30+');

