INSERT INTO security_groups (group_name) VALUES('Venner');
INSERT INTO security_groups (group_name) VALUES('Familie');
INSERT INTO security_groups (group_name) VALUES('Vedligeholdere');

INSERT INTO recipe_ethnicity (ethnic_desc) VALUES ('Amerikansk');
INSERT INTO recipe_ethnicity (ethnic_desc) VALUES ('Kinesisk');
INSERT INTO recipe_ethnicity (ethnic_desc) VALUES ('Tysk');
INSERT INTO recipe_ethnicity (ethnic_desc) VALUES ('Græsk');
INSERT INTO recipe_ethnicity (ethnic_desc) VALUES ('Italiensk');
INSERT INTO recipe_ethnicity (ethnic_desc) VALUES ('Japansk');
INSERT INTO recipe_ethnicity (ethnic_desc) VALUES ('Mexikansk');
INSERT INTO recipe_ethnicity (ethnic_desc) VALUES ('Ingen');
INSERT INTO recipe_ethnicity (ethnic_desc) VALUES ('Slavisk');
INSERT INTO recipe_ethnicity (ethnic_desc) VALUES ('Orientalsk');
INSERT INTO recipe_ethnicity (ethnic_desc) VALUES ('Dansk');
INSERT INTO recipe_ethnicity (ethnic_desc) VALUES ('Nordisk');
INSERT INTO recipe_ethnicity (ethnic_desc) VALUES ('Mellemøsten');

INSERT INTO recipe_units (unit_id,unit_desc,unit_abbr) VALUES (1,'Styk','stk');
INSERT INTO recipe_units (unit_id,unit_desc,unit_abbr) VALUES (2,'Skive','slive');
INSERT INTO recipe_units (unit_id,unit_desc,unit_abbr) VALUES (3,'Clove','clv');
INSERT INTO recipe_units (unit_id,unit_desc,unit_abbr) VALUES (4,'Presset','presset');
INSERT INTO recipe_units (unit_id,unit_desc,unit_abbr) VALUES (5,'Pakke','pk');
INSERT INTO recipe_units (unit_id,unit_desc,unit_abbr) VALUES (6,'Dåse','ds');
INSERT INTO recipe_units (unit_id,unit_desc,unit_abbr) VALUES (7,'Dråbe','dråbe');
INSERT INTO recipe_units (unit_id,unit_desc,unit_abbr) VALUES (8,'Bundt','bdt.');
INSERT INTO recipe_units (unit_id,unit_desc,unit_abbr) VALUES (9,'Stænk','stænk');
INSERT INTO recipe_units (unit_id,unit_desc,unit_abbr) VALUES (10,'Karton','kt.');
INSERT INTO recipe_units (unit_id,unit_desc,unit_abbr) VALUES (11,'Kop','kop');
INSERT INTO recipe_units (unit_id,unit_desc,unit_abbr) VALUES (12,'Spiseske','spsk');
INSERT INTO recipe_units (unit_id,unit_desc,unit_abbr) VALUES (13,'Teske','tsk');
INSERT INTO recipe_units (unit_id,unit_desc,unit_abbr) VALUES (14,'Pund','pund');
INSERT INTO recipe_units (unit_id,unit_desc,unit_abbr) VALUES (15,'Ounce','oz');
INSERT INTO recipe_units (unit_id,unit_desc,unit_abbr) VALUES (16,'Pint','pt');
INSERT INTO recipe_units (unit_id,unit_desc,unit_abbr) VALUES (17,'Quart','q');
INSERT INTO recipe_units (unit_id,unit_desc,unit_abbr) VALUES (18,'Gallon','gal');
INSERT INTO recipe_units (unit_id,unit_desc,unit_abbr) VALUES (19,'Milligram','mg');
INSERT INTO recipe_units (unit_id,unit_desc,unit_abbr) VALUES (20,'Centigram','cg');
INSERT INTO recipe_units (unit_id,unit_desc,unit_abbr) VALUES (21,'Gram','g');
INSERT INTO recipe_units (unit_id,unit_desc,unit_abbr) VALUES (22,'Kilogram','kg');
INSERT INTO recipe_units (unit_id,unit_desc,unit_abbr) VALUES (23,'Milliliter','ml');
INSERT INTO recipe_units (unit_id,unit_desc,unit_abbr) VALUES (24,'Centiliter','cl');
INSERT INTO recipe_units (unit_id,unit_desc,unit_abbr) VALUES (25,'Liter','l');

INSERT INTO recipe_locations (location_desc) VALUES ('Alkohol');
INSERT INTO recipe_locations (location_desc) VALUES ('Bagværk');
INSERT INTO recipe_locations (location_desc) VALUES ('Bagværks-tilbehør');
INSERT INTO recipe_locations (location_desc) VALUES ('Bønner');
INSERT INTO recipe_locations (location_desc) VALUES ('Brød');
INSERT INTO recipe_locations (location_desc) VALUES ('Morgemad');
INSERT INTO recipe_locations (location_desc) VALUES ('Slik');
INSERT INTO recipe_locations (location_desc) VALUES ('Frugt på Dåse');
INSERT INTO recipe_locations (location_desc) VALUES ('Kød (og fisk) på dåse');
INSERT INTO recipe_locations (location_desc) VALUES ('Grøntsager på dåse');
INSERT INTO recipe_locations (location_desc) VALUES ('Kaffe, The &amp; Kakao');
INSERT INTO recipe_locations (location_desc) VALUES ('Krydderier');
INSERT INTO recipe_locations (location_desc) VALUES ('Kager');
INSERT INTO recipe_locations (location_desc) VALUES ('Kiks');
INSERT INTO recipe_locations (location_desc) VALUES ('Mejeri produkter');
INSERT INTO recipe_locations (location_desc) VALUES ('Delikatesse');
INSERT INTO recipe_locations (location_desc) VALUES ('Drink mix');
INSERT INTO recipe_locations (location_desc) VALUES ('Køkkenrylle');
INSERT INTO recipe_locations (location_desc) VALUES ('Mad Opbevaring');
INSERT INTO recipe_locations (location_desc) VALUES ('Gratis');
INSERT INTO recipe_locations (location_desc) VALUES ('Frossen Mad');
INSERT INTO recipe_locations (location_desc) VALUES ('HABA');
INSERT INTO recipe_locations (location_desc) VALUES ('Håndsæbe');
INSERT INTO recipe_locations (location_desc) VALUES ('Morgenmads Produkter');
INSERT INTO recipe_locations (location_desc) VALUES ('Rengøringsmidler');
INSERT INTO recipe_locations (location_desc) VALUES ('Juice');
INSERT INTO recipe_locations (location_desc) VALUES ('Kosher/Etnisk');
INSERT INTO recipe_locations (location_desc) VALUES ('Vaskemidler');
INSERT INTO recipe_locations (location_desc) VALUES ('Kød');
INSERT INTO recipe_locations (location_desc) VALUES ('Natural &amp; Organic');
INSERT INTO recipe_locations (location_desc) VALUES ('Olie/Eddike/Dressinger');
INSERT INTO recipe_locations (location_desc) VALUES ('Pandekager &amp; Sirup');
INSERT INTO recipe_locations (location_desc) VALUES ('Engangs Service');
INSERT INTO recipe_locations (location_desc) VALUES ('Pasta &amp; Sauce');
INSERT INTO recipe_locations (location_desc) VALUES ('Peanut Smør/Marmelade/Honning');
INSERT INTO recipe_locations (location_desc) VALUES ('Frugt og Grønt');
INSERT INTO recipe_locations (location_desc) VALUES ('Ris');
INSERT INTO recipe_locations (location_desc) VALUES ('Saltede Snacks &amp; Chips');
INSERT INTO recipe_locations (location_desc) VALUES ('Seafood');
INSERT INTO recipe_locations (location_desc) VALUES ('Sodavand');
INSERT INTO recipe_locations (location_desc) VALUES ('Suppe');
INSERT INTO recipe_locations (location_desc) VALUES ('Krydderier');
INSERT INTO recipe_locations (location_desc) VALUES ('Toilet Papir');

INSERT INTO recipe_bases (base_desc) VALUES ('Oksekød');
INSERT INTO recipe_bases (base_desc) VALUES ('Brød');
INSERT INTO recipe_bases (base_desc) VALUES ('Æg');
INSERT INTO recipe_bases (base_desc) VALUES ('Frugt');
INSERT INTO recipe_bases (base_desc) VALUES ('Frø/Korn');
INSERT INTO recipe_bases (base_desc) VALUES ('Lam');
INSERT INTO recipe_bases (base_desc) VALUES ('Andet');
INSERT INTO recipe_bases (base_desc) VALUES ('Pasta');
INSERT INTO recipe_bases (base_desc) VALUES ('Svinekød');
INSERT INTO recipe_bases (base_desc) VALUES ('Fjerkræ');
INSERT INTO recipe_bases (base_desc) VALUES ('Seafood / Fisk');
INSERT INTO recipe_bases (base_desc) VALUES ('Grøntsager');

INSERT INTO recipe_prep_time (time_desc) VALUES ('0 Minutter');
INSERT INTO recipe_prep_time (time_desc) VALUES ('1-10 Minutter');
INSERT INTO recipe_prep_time (time_desc) VALUES ('10-30 Minutter');
INSERT INTO recipe_prep_time (time_desc) VALUES ('30-60 Minutter');
INSERT INTO recipe_prep_time (time_desc) VALUES ('60+ Minutter');

INSERT INTO recipe_difficulty (difficult_desc) VALUES ('Let');
INSERT INTO recipe_difficulty (difficult_desc) VALUES ('Mellemsvært');
INSERT INTO recipe_difficulty (difficult_desc) VALUES ('Svært');
INSERT INTO recipe_difficulty (difficult_desc) VALUES ('Expert');

INSERT INTO recipe_courses (course_desc) VALUES ('Morgenmad');
INSERT INTO recipe_courses (course_desc) VALUES ('Snack');
INSERT INTO recipe_courses (course_desc) VALUES ('Frokost');
INSERT INTO recipe_courses (course_desc) VALUES ('Forret');
INSERT INTO recipe_courses (course_desc) VALUES ('Mellem måltid');
INSERT INTO recipe_courses (course_desc) VALUES ('Mellemret');
INSERT INTO recipe_courses (course_desc) VALUES ('Dessert');
INSERT INTO recipe_courses (course_desc) VALUES ('Drikkevarer');

INSERT INTO recipe_meals (meal_name) VALUES ('Morgenmad');
INSERT INTO recipe_meals (meal_name) VALUES ('Brunch');
INSERT INTO recipe_meals (meal_name) VALUES ('Frokost');
INSERT INTO recipe_meals (meal_name) VALUES ('Eftermiddags Snack');
INSERT INTO recipe_meals (meal_name) VALUES ('Middagsmad');
INSERT INTO recipe_meals (meal_name) VALUES ('Dessert');

INSERT INTO recipe_prices (price_desc) VALUES ('0-100 DKR');
INSERT INTO recipe_prices (price_desc) VALUES ('100-150 DKR');
INSERT INTO recipe_prices (price_desc) VALUES ('150-200 DKR');
INSERT INTO recipe_prices (price_desc) VALUES ('200-250 DKR');
INSERT INTO recipe_prices (price_desc) VALUES ('250-300 DKR');
INSERT INTO recipe_prices (price_desc) VALUES ('300+ DKR');

