INSERT INTO security_groups (group_name) VALUES('Vänner');
INSERT INTO security_groups (group_name) VALUES('Familj');
INSERT INTO security_groups (group_name) VALUES('Ansvariga');

INSERT INTO recipe_ethnicity (ethnic_desc) VALUES ('Svenskt');
INSERT INTO recipe_ethnicity (ethnic_desc) VALUES ('Amerikanst');
INSERT INTO recipe_ethnicity (ethnic_desc) VALUES ('Kinesiskt');
INSERT INTO recipe_ethnicity (ethnic_desc) VALUES ('Tyskt');
INSERT INTO recipe_ethnicity (ethnic_desc) VALUES ('Grekiskt');
INSERT INTO recipe_ethnicity (ethnic_desc) VALUES ('Italienskt');
INSERT INTO recipe_ethnicity (ethnic_desc) VALUES ('Japanskt');
INSERT INTO recipe_ethnicity (ethnic_desc) VALUES ('Mexikanskt');
INSERT INTO recipe_ethnicity (ethnic_desc) VALUES ('Slaviskt');
INSERT INTO recipe_ethnicity (ethnic_desc) VALUES ('Franskt');
INSERT INTO recipe_ethnicity (ethnic_desc) VALUES ('Australiensiskt');
INSERT INTO recipe_ethnicity (ethnic_desc) VALUES ('Odefinerat');

INSERT INTO recipe_units (unit_id,unit_desc,unit_abbr) VALUES (1,'styck','stk');
INSERT INTO recipe_units (unit_id,unit_desc,unit_abbr) VALUES (2,'skivor','skivor');
INSERT INTO recipe_units (unit_id,unit_desc,unit_abbr) VALUES (3,'Clove','clv');
INSERT INTO recipe_units (unit_id,unit_desc,unit_abbr) VALUES (4,'nypa','nypa');
INSERT INTO recipe_units (unit_id,unit_desc,unit_abbr) VALUES (5,'paket','pkt');
INSERT INTO recipe_units (unit_id,unit_desc,unit_abbr) VALUES (6,'burkar','burk');
INSERT INTO recipe_units (unit_id,unit_desc,unit_abbr) VALUES (7,'droppar','droppar');
INSERT INTO recipe_units (unit_id,unit_desc,unit_abbr) VALUES (8,'bunt','bunt');
INSERT INTO recipe_units (unit_id,unit_desc,unit_abbr) VALUES (9,'stänk','stänk');
INSERT INTO recipe_units (unit_id,unit_desc,unit_abbr) VALUES (10,'kartong','kartong');
INSERT INTO recipe_units (unit_id,unit_desc,unit_abbr) VALUES (11,'US cup','c');
INSERT INTO recipe_units (unit_id,unit_desc,unit_abbr) VALUES (12,'US Tablespoon','T');
INSERT INTO recipe_units (unit_id,unit_desc,unit_abbr) VALUES (13,'US Teaspoon','t');
INSERT INTO recipe_units (unit_id,unit_desc,unit_abbr) VALUES (14,'Pound','lb');
INSERT INTO recipe_units (unit_id,unit_desc,unit_abbr) VALUES (15,'Ounce','oz');
INSERT INTO recipe_units (unit_id,unit_desc,unit_abbr) VALUES (16,'US Pint','pt');
INSERT INTO recipe_units (unit_id,unit_desc,unit_abbr) VALUES (17,'US Quart','q');
INSERT INTO recipe_units (unit_id,unit_desc,unit_abbr) VALUES (18,'US Gallon','gal');
INSERT INTO recipe_units (unit_id,unit_desc,unit_abbr) VALUES (19,'milligram','mg');
INSERT INTO recipe_units (unit_id,unit_desc,unit_abbr) VALUES (20,'centigram','cg');
INSERT INTO recipe_units (unit_id,unit_desc,unit_abbr) VALUES (21,'gram','g');
INSERT INTO recipe_units (unit_id,unit_desc,unit_abbr) VALUES (22,'kilogram','kg');
INSERT INTO recipe_units (unit_id,unit_desc,unit_abbr) VALUES (23,'kryddmått','krm');
INSERT INTO recipe_units (unit_id,unit_desc,unit_abbr) VALUES (24,'centiliter','cl');
INSERT INTO recipe_units (unit_id,unit_desc,unit_abbr) VALUES (25,'liter','l');
INSERT INTO recipe_units (unit_id,unit_desc,unit_abbr) VALUES (26,'deciliter','dl');
INSERT INTO recipe_units (unit_id,unit_desc,unit_abbr) VALUES (27,'matsked','tbsp');
INSERT INTO recipe_units (unit_id,unit_desc,unit_abbr) VALUES (28,'tesked','tsp');

INSERT INTO recipe_locations (location_desc) VALUES ('Alkohol');
INSERT INTO recipe_locations (location_desc) VALUES ('Bageri');
INSERT INTO recipe_locations (location_desc) VALUES ('Bak-tillbehör');
INSERT INTO recipe_locations (location_desc) VALUES ('Bönor');
INSERT INTO recipe_locations (location_desc) VALUES ('Bröd');
INSERT INTO recipe_locations (location_desc) VALUES ('Godis');
INSERT INTO recipe_locations (location_desc) VALUES ('Konserverad frukt');
INSERT INTO recipe_locations (location_desc) VALUES ('Konserverat kött &amp; fisk');
INSERT INTO recipe_locations (location_desc) VALUES ('Konserverade grönsaker');
INSERT INTO recipe_locations (location_desc) VALUES ('Kaffe, Te &amp; Choklad');
INSERT INTO recipe_locations (location_desc) VALUES ('Condiments');
INSERT INTO recipe_locations (location_desc) VALUES ('Kakor');
INSERT INTO recipe_locations (location_desc) VALUES ('Mejeri');
INSERT INTO recipe_locations (location_desc) VALUES ('Delikatess');
INSERT INTO recipe_locations (location_desc) VALUES ('Drinkmixer');
INSERT INTO recipe_locations (location_desc) VALUES ('Bomull');
INSERT INTO recipe_locations (location_desc) VALUES ('Food Storage');
INSERT INTO recipe_locations (location_desc) VALUES ('Gratis');
INSERT INTO recipe_locations (location_desc) VALUES ('Frysta varor');
INSERT INTO recipe_locations (location_desc) VALUES ('Egenvård');
INSERT INTO recipe_locations (location_desc) VALUES ('Tvål');
INSERT INTO recipe_locations (location_desc) VALUES ('Frukostflingor');
INSERT INTO recipe_locations (location_desc) VALUES ('Rengöringsmedel');
INSERT INTO recipe_locations (location_desc) VALUES ('Juice &amp; Cocktail');
INSERT INTO recipe_locations (location_desc) VALUES ('Kosher/Ethniskt');
INSERT INTO recipe_locations (location_desc) VALUES ('Tvättmedel');
INSERT INTO recipe_locations (location_desc) VALUES ('Kött');
INSERT INTO recipe_locations (location_desc) VALUES ('Naturligt &amp; Organiskt');
INSERT INTO recipe_locations (location_desc) VALUES ('Olja/Vinäger/Dressingar');
INSERT INTO recipe_locations (location_desc) VALUES ('Papperstallrikar');
INSERT INTO recipe_locations (location_desc) VALUES ('Pasta &amp; sås');
INSERT INTO recipe_locations (location_desc) VALUES ('Ris');
INSERT INTO recipe_locations (location_desc) VALUES ('Chips etc');
INSERT INTO recipe_locations (location_desc) VALUES ('Fisk och skaldjur');
INSERT INTO recipe_locations (location_desc) VALUES ('Läsk');
INSERT INTO recipe_locations (location_desc) VALUES ('Soppa');
INSERT INTO recipe_locations (location_desc) VALUES ('Kryddor');
INSERT INTO recipe_locations (location_desc) VALUES ('Toalettpapper');

INSERT INTO recipe_bases (base_desc) VALUES ('Kött');
INSERT INTO recipe_bases (base_desc) VALUES ('Bröd');
INSERT INTO recipe_bases (base_desc) VALUES ('Ägg');
INSERT INTO recipe_bases (base_desc) VALUES ('Frukt');
INSERT INTO recipe_bases (base_desc) VALUES ('Korn');
INSERT INTO recipe_bases (base_desc) VALUES ('Lamm');
INSERT INTO recipe_bases (base_desc) VALUES ('Pasta');
INSERT INTO recipe_bases (base_desc) VALUES ('Fläsk/Skinka');
INSERT INTO recipe_bases (base_desc) VALUES ('Fågel');
INSERT INTO recipe_bases (base_desc) VALUES ('Fisk och skaldjur');
INSERT INTO recipe_bases (base_desc) VALUES ('Grönsaker');
INSERT INTO recipe_bases (base_desc) VALUES ('Annat');

INSERT INTO recipe_prep_time (time_desc) VALUES ('0 Minuter');
INSERT INTO recipe_prep_time (time_desc) VALUES ('1-10 Minuter');
INSERT INTO recipe_prep_time (time_desc) VALUES ('10-30 Minuter');
INSERT INTO recipe_prep_time (time_desc) VALUES ('30-60 Minuter');
INSERT INTO recipe_prep_time (time_desc) VALUES ('60+ Minuter');

INSERT INTO recipe_difficulty (difficult_desc) VALUES ('Lätt');
INSERT INTO recipe_difficulty (difficult_desc) VALUES ('Normalsvårt');
INSERT INTO recipe_difficulty (difficult_desc) VALUES ('Svårt');
INSERT INTO recipe_difficulty (difficult_desc) VALUES ('Expert');

INSERT INTO recipe_courses (course_desc) VALUES ('Frukost');
INSERT INTO recipe_courses (course_desc) VALUES ('Mellanmål');
INSERT INTO recipe_courses (course_desc) VALUES ('Lunch');
INSERT INTO recipe_courses (course_desc) VALUES ('Förrätt');
INSERT INTO recipe_courses (course_desc) VALUES ('Middag');
INSERT INTO recipe_courses (course_desc) VALUES ('Tilltugg');
INSERT INTO recipe_courses (course_desc) VALUES ('Efterrätt');
INSERT INTO recipe_courses (course_desc) VALUES ('Dryck');

INSERT INTO recipe_meals (meal_name) VALUES ('Frukost');
INSERT INTO recipe_meals (meal_name) VALUES ('Brunch');
INSERT INTO recipe_meals (meal_name) VALUES ('Lunch');
INSERT INTO recipe_meals (meal_name) VALUES ('Mellanmål');
INSERT INTO recipe_meals (meal_name) VALUES ('Middag');
INSERT INTO recipe_meals (meal_name) VALUES ('Efterrätt');

INSERT INTO recipe_prices (price_desc) VALUES ('0-50 kr');
INSERT INTO recipe_prices (price_desc) VALUES ('50-100 kr');
INSERT INTO recipe_prices (price_desc) VALUES ('100-150 kr');
INSERT INTO recipe_prices (price_desc) VALUES ('150-250 kr');
INSERT INTO recipe_prices (price_desc) VALUES ('250-400 kr');
INSERT INTO recipe_prices (price_desc) VALUES ('400+ kr');
