INSERT INTO recipe_bases (base_id, base_desc) VALUES (1, 'Dana Eti');
INSERT INTO recipe_bases (base_id, base_desc) VALUES (2, 'Ekmek');
INSERT INTO recipe_bases (base_id, base_desc) VALUES (3, 'Yumurta');
INSERT INTO recipe_bases (base_id, base_desc) VALUES (4, 'Meyve');
INSERT INTO recipe_bases (base_id, base_desc) VALUES (5, 'Tahýl');
INSERT INTO recipe_bases (base_id, base_desc) VALUES (6, 'Kuzu');
INSERT INTO recipe_bases (base_id, base_desc) VALUES (7, 'Diðer');
INSERT INTO recipe_bases (base_id, base_desc) VALUES (8, 'Hamur Ýþleri');
INSERT INTO recipe_bases (base_id, base_desc) VALUES (9, 'Tavuk');
INSERT INTO recipe_bases (base_id, base_desc) VALUES (10, 'Hindi');
INSERT INTO recipe_bases (base_id, base_desc) VALUES (11, 'Deniz Mahsulleri');
INSERT INTO recipe_bases (base_id, base_desc) VALUES (12, 'Sebze');

INSERT INTO recipe_courses (course_id, course_desc) VALUES (1, 'Kahvaltý');
INSERT INTO recipe_courses (course_id, course_desc) VALUES (2, 'Atýþtýrma');
INSERT INTO recipe_courses (course_id, course_desc) VALUES (3, 'Ýþtah Açýcý');
INSERT INTO recipe_courses (course_id, course_desc) VALUES (4, 'Aperatif');
INSERT INTO recipe_courses (course_id, course_desc) VALUES (5, 'Garnitür');
INSERT INTO recipe_courses (course_id, course_desc) VALUES (6, 'Baþlangýç');
INSERT INTO recipe_courses (course_id, course_desc) VALUES (7, 'Tatlý');
INSERT INTO recipe_courses (course_id, course_desc) VALUES (8, 'Ýçecek');

INSERT INTO recipe_difficulty (difficult_id, difficult_desc) VALUES (1, 'Kolay');
INSERT INTO recipe_difficulty (difficult_id, difficult_desc) VALUES (2, 'Orta');
INSERT INTO recipe_difficulty (difficult_id, difficult_desc) VALUES (3, 'Zor');
INSERT INTO recipe_difficulty (difficult_id, difficult_desc) VALUES (4, 'Uzman');

INSERT INTO recipe_ethnicity (ethnic_id, ethnic_desc) VALUES (1, 'Amerikan');
INSERT INTO recipe_ethnicity (ethnic_id, ethnic_desc) VALUES (2, 'Çin');
INSERT INTO recipe_ethnicity (ethnic_id, ethnic_desc) VALUES (3, 'Alman');
INSERT INTO recipe_ethnicity (ethnic_id, ethnic_desc) VALUES (4, 'Yunan');
INSERT INTO recipe_ethnicity (ethnic_id, ethnic_desc) VALUES (5, 'Ýtalyan');
INSERT INTO recipe_ethnicity (ethnic_id, ethnic_desc) VALUES (6, 'Japon');
INSERT INTO recipe_ethnicity (ethnic_id, ethnic_desc) VALUES (7, 'Meksika');
INSERT INTO recipe_ethnicity (ethnic_id, ethnic_desc) VALUES (8, 'Orta Doðu');
INSERT INTO recipe_ethnicity (ethnic_id, ethnic_desc) VALUES (9, 'Diðer');
INSERT INTO recipe_ethnicity (ethnic_id, ethnic_desc) VALUES (10, 'Slav');
INSERT INTO recipe_ethnicity (ethnic_id, ethnic_desc) VALUES (11, 'Türk');
INSERT INTO recipe_ethnicity (ethnic_id, ethnic_desc) VALUES (12, 'Azeri');

INSERT INTO recipe_locations (location_id, location_desc) VALUES (1, 'Alcohol');
INSERT INTO recipe_locations (location_id, location_desc) VALUES (2, 'Bakery');
INSERT INTO recipe_locations (location_id, location_desc) VALUES (3, 'Baking needs');
INSERT INTO recipe_locations (location_id, location_desc) VALUES (4, 'Beans');
INSERT INTO recipe_locations (location_id, location_desc) VALUES (5, 'Bread');
INSERT INTO recipe_locations (location_id, location_desc) VALUES (6, 'Breakfast bars');
INSERT INTO recipe_locations (location_id, location_desc) VALUES (7, 'Candy');
INSERT INTO recipe_locations (location_id, location_desc) VALUES (8, 'Canned Fruit');
INSERT INTO recipe_locations (location_id, location_desc) VALUES (9, 'Canned Meat &amp; Fish');
INSERT INTO recipe_locations (location_id, location_desc) VALUES (10, 'Canned Vegetables');
INSERT INTO recipe_locations (location_id, location_desc) VALUES (11, 'Coffee, Tea &amp; Cocoa');
INSERT INTO recipe_locations (location_id, location_desc) VALUES (12, 'Condiments');
INSERT INTO recipe_locations (location_id, location_desc) VALUES (13, 'Cookies');
INSERT INTO recipe_locations (location_id, location_desc) VALUES (14, 'Crackers');
INSERT INTO recipe_locations (location_id, location_desc) VALUES (15, 'Dairy');
INSERT INTO recipe_locations (location_id, location_desc) VALUES (16, 'Deli');
INSERT INTO recipe_locations (location_id, location_desc) VALUES (17, 'Drink mix');
INSERT INTO recipe_locations (location_id, location_desc) VALUES (18, 'Facial Tissue');
INSERT INTO recipe_locations (location_id, location_desc) VALUES (19, 'Food Storage');
INSERT INTO recipe_locations (location_id, location_desc) VALUES (20, 'Free');
INSERT INTO recipe_locations (location_id, location_desc) VALUES (21, 'Frozen Foods');
INSERT INTO recipe_locations (location_id, location_desc) VALUES (22, 'HABA');
INSERT INTO recipe_locations (location_id, location_desc) VALUES (23, 'Hand Soap');
INSERT INTO recipe_locations (location_id, location_desc) VALUES (24, 'Hot &amp; Cold Cereal');
INSERT INTO recipe_locations (location_id, location_desc) VALUES (25, 'Household Cleaners');
INSERT INTO recipe_locations (location_id, location_desc) VALUES (26, 'Juice &amp; Cocktail');
INSERT INTO recipe_locations (location_id, location_desc) VALUES (27, 'Kosher/Ethnic');
INSERT INTO recipe_locations (location_id, location_desc) VALUES (28, 'Laundry Detergents');
INSERT INTO recipe_locations (location_id, location_desc) VALUES (29, 'Meat');
INSERT INTO recipe_locations (location_id, location_desc) VALUES (30, 'Natural &amp; Organic');
INSERT INTO recipe_locations (location_id, location_desc) VALUES (31, 'Oil/Vinegar/Dressings');
INSERT INTO recipe_locations (location_id, location_desc) VALUES (32, 'Pancakes &amp; Syrup');
INSERT INTO recipe_locations (location_id, location_desc) VALUES (33, 'Paper Serving Ware');
INSERT INTO recipe_locations (location_id, location_desc) VALUES (34, 'Pasta &amp; Sauce');
INSERT INTO recipe_locations (location_id, location_desc) VALUES (35, 'Peanut Butter/Jelly/Honey');
INSERT INTO recipe_locations (location_id, location_desc) VALUES (36, 'Produce');
INSERT INTO recipe_locations (location_id, location_desc) VALUES (37, 'Rice');
INSERT INTO recipe_locations (location_id, location_desc) VALUES (38, 'Salty Snacks &amp; Chips');
INSERT INTO recipe_locations (location_id, location_desc) VALUES (39, 'Seafood');
INSERT INTO recipe_locations (location_id, location_desc) VALUES (40, 'Soda pop');
INSERT INTO recipe_locations (location_id, location_desc) VALUES (41, 'Soup');
INSERT INTO recipe_locations (location_id, location_desc) VALUES (42, 'Spices');
INSERT INTO recipe_locations (location_id, location_desc) VALUES (43, 'Toilet Paper');

INSERT INTO recipe_meals (meal_id, meal_name) VALUES (1, 'Kahvaltý');
INSERT INTO recipe_meals (meal_id, meal_name) VALUES (2, 'Brunch');
INSERT INTO recipe_meals (meal_id, meal_name) VALUES (3, 'Lunch');
INSERT INTO recipe_meals (meal_id, meal_name) VALUES (4, 'Afternoon Snack');
INSERT INTO recipe_meals (meal_id, meal_name) VALUES (5, 'Dinner');
INSERT INTO recipe_meals (meal_id, meal_name) VALUES (6, 'Tatlý');

INSERT INTO recipe_prep_time (time_id, time_desc) VALUES (1, '- 1 Dakika');
INSERT INTO recipe_prep_time (time_id, time_desc) VALUES (2, '1-10 Dakika');
INSERT INTO recipe_prep_time (time_id, time_desc) VALUES (3, '10-30 Dakika');
INSERT INTO recipe_prep_time (time_id, time_desc) VALUES (4, '30-60 Dakika');
INSERT INTO recipe_prep_time (time_id, time_desc) VALUES (5, '60+ Dakika');

INSERT INTO recipe_prices (price_id, price_desc) VALUES (1, '$0-$10');
INSERT INTO recipe_prices (price_id, price_desc) VALUES (2, '$10-$15');
INSERT INTO recipe_prices (price_id, price_desc) VALUES (3, '$15-$20');
INSERT INTO recipe_prices (price_id, price_desc) VALUES (4, '$20-$25');
INSERT INTO recipe_prices (price_id, price_desc) VALUES (5, '$25-$30');
INSERT INTO recipe_prices (price_id, price_desc) VALUES (6, '$30+');

INSERT INTO recipe_units (unit_id, unit_desc, unit_abbr) VALUES (1, 'Unit', 'ea');
INSERT INTO recipe_units (unit_id, unit_desc, unit_abbr) VALUES (2, 'Slice', 'sli');
INSERT INTO recipe_units (unit_id, unit_desc, unit_abbr) VALUES (3, 'Clove', 'clv');
INSERT INTO recipe_units (unit_id, unit_desc, unit_abbr) VALUES (4, 'Pinch', 'pn');
INSERT INTO recipe_units (unit_id, unit_desc, unit_abbr) VALUES (5, 'Package', 'pk');
INSERT INTO recipe_units (unit_id, unit_desc, unit_abbr) VALUES (6, 'Can', 'cn');
INSERT INTO recipe_units (unit_id, unit_desc, unit_abbr) VALUES (7, 'Drop', 'dr');
INSERT INTO recipe_units (unit_id, unit_desc, unit_abbr) VALUES (8, 'Bunch', 'bn');
INSERT INTO recipe_units (unit_id, unit_desc, unit_abbr) VALUES (9, 'Dash', 'ds');
INSERT INTO recipe_units (unit_id, unit_desc, unit_abbr) VALUES (10, 'Carton', 'ct');
INSERT INTO recipe_units (unit_id, unit_desc, unit_abbr) VALUES (11, 'Cup', 'c');
INSERT INTO recipe_units (unit_id, unit_desc, unit_abbr) VALUES (12, 'Tablespoon', 'T');
INSERT INTO recipe_units (unit_id, unit_desc, unit_abbr) VALUES (13, 'Teaspoon', 't');
INSERT INTO recipe_units (unit_id, unit_desc, unit_abbr) VALUES (14, 'Pound', 'lb');
INSERT INTO recipe_units (unit_id, unit_desc, unit_abbr) VALUES (15, 'Ounce', 'oz');
INSERT INTO recipe_units (unit_id, unit_desc, unit_abbr) VALUES (16, 'Pint', 'pt');
INSERT INTO recipe_units (unit_id, unit_desc, unit_abbr) VALUES (17, 'Quart', 'q');
INSERT INTO recipe_units (unit_id, unit_desc, unit_abbr) VALUES (18, 'Gallon', 'gal');
INSERT INTO recipe_units (unit_id, unit_desc, unit_abbr) VALUES (19, 'Milligram', 'mg');
INSERT INTO recipe_units (unit_id, unit_desc, unit_abbr) VALUES (20, 'Centigram', 'cg');
INSERT INTO recipe_units (unit_id, unit_desc, unit_abbr) VALUES (21, 'Gram', 'g');
INSERT INTO recipe_units (unit_id, unit_desc, unit_abbr) VALUES (22, 'Kilogram', 'kg');
INSERT INTO recipe_units (unit_id, unit_desc, unit_abbr) VALUES (23, 'Milliliter', 'ml');
INSERT INTO recipe_units (unit_id, unit_desc, unit_abbr) VALUES (24, 'Centiliter', 'cl');
INSERT INTO recipe_units (unit_id, unit_desc, unit_abbr) VALUES (25, 'Liter', 'l');
INSERT INTO recipe_units (unit_id, unit_desc, unit_abbr) VALUES (26, 'Deciliter', 'dl');
INSERT INTO recipe_units (unit_id, unit_desc, unit_abbr) VALUES (27, 'Tablespoon_m', 'tbsp');
INSERT INTO recipe_units (unit_id, unit_desc, unit_abbr) VALUES (28, 'Teaspoon_m', 'tsp');

INSERT INTO security_groups (group_id, group_name) VALUES (1, 'Arkadaþlar');
INSERT INTO security_groups (group_id, group_name) VALUES (2, 'Aile');
INSERT INTO security_groups (group_id, group_name) VALUES (3, 'Yöneticiler');
