INSERT INTO security_groups (group_name) VALUES('Freunde');
INSERT INTO security_groups (group_name) VALUES('Familie');
INSERT INTO security_groups (group_name) VALUES('Verwalter');

INSERT INTO recipe_ethnicity (ethnic_desc) VALUES ('Italienisch');
INSERT INTO recipe_ethnicity (ethnic_desc) VALUES ('Chinesisch');
INSERT INTO recipe_ethnicity (ethnic_desc) VALUES ('Japanisch');
INSERT INTO recipe_ethnicity (ethnic_desc) VALUES ('Mexikanisch');
INSERT INTO recipe_ethnicity (ethnic_desc) VALUES ('Amerikanisch');
INSERT INTO recipe_ethnicity (ethnic_desc) VALUES ('Australisch');
INSERT INTO recipe_ethnicity (ethnic_desc) VALUES ('Spanisch');
INSERT INTO recipe_ethnicity (ethnic_desc) VALUES ('Asiatisch');
INSERT INTO recipe_ethnicity (ethnic_desc) VALUES ('Französisch');
INSERT INTO recipe_ethnicity (ethnic_desc) VALUES ('Skandinavisch');

INSERT INTO recipe_units (unit_id,unit_desc,unit_abbr) VALUES ('1','Einheit','eh');
INSERT INTO recipe_units (unit_id,unit_desc,unit_abbr) VALUES ('2','Scheibe','sch');
INSERT INTO recipe_units (unit_id,unit_desc,unit_abbr) VALUES ('3','Nelke','ne');
INSERT INTO recipe_units (unit_id,unit_desc,unit_abbr) VALUES ('4','Priese','pr');
INSERT INTO recipe_units (unit_id,unit_desc,unit_abbr) VALUES ('5','Packung','pk');
INSERT INTO recipe_units (unit_id,unit_desc,unit_abbr) VALUES ('6','Dose','ds');
INSERT INTO recipe_units (unit_id,unit_desc,unit_abbr) VALUES ('7','Tropfen','tr');
INSERT INTO recipe_units (unit_id,unit_desc,unit_abbr) VALUES ('8','Bündel','bd');
INSERT INTO recipe_units (unit_id,unit_desc,unit_abbr) VALUES ('9','Spritzer','spr');
INSERT INTO recipe_units (unit_id,unit_desc,unit_abbr) VALUES ('10','Karton','kat');
INSERT INTO recipe_units (unit_id,unit_desc,unit_abbr) VALUES ('11','Tasse','ta');
INSERT INTO recipe_units (unit_id,unit_desc,unit_abbr) VALUES ('12','Esslöffel','el');
INSERT INTO recipe_units (unit_id,unit_desc,unit_abbr) VALUES ('13','Teelöfel','tl');
INSERT INTO recipe_units (unit_id,unit_desc,unit_abbr) VALUES ('14','Pfund','pfd');
INSERT INTO recipe_units (unit_id,unit_desc,unit_abbr) VALUES ('15','Unze','oz');
INSERT INTO recipe_units (unit_id,unit_desc,unit_abbr) VALUES ('16','Pint','pt');
INSERT INTO recipe_units (unit_id,unit_desc,unit_abbr) VALUES ('17','Quart','q');
INSERT INTO recipe_units (unit_id,unit_desc,unit_abbr) VALUES ('18','Gallone','gal');
INSERT INTO recipe_units (unit_id,unit_desc,unit_abbr) VALUES ('19','Milligramm','mg');
INSERT INTO recipe_units (unit_id,unit_desc,unit_abbr) VALUES ('20','Centigramm','cg');
INSERT INTO recipe_units (unit_id,unit_desc,unit_abbr) VALUES ('21','Gramm','g');
INSERT INTO recipe_units (unit_id,unit_desc,unit_abbr) VALUES ('22','Kilogramm','kg');
INSERT INTO recipe_units (unit_id,unit_desc,unit_abbr) VALUES ('23','Milliliter','ml');
INSERT INTO recipe_units (unit_id,unit_desc,unit_abbr) VALUES ('24','Centiliter','cl');
INSERT INTO recipe_units (unit_id,unit_desc,unit_abbr) VALUES ('25','Liter','l');
INSERT INTO recipe_units (unit_id,unit_desc,unit_abbr) VALUES ('26','Deziliter', 'dl');

INSERT INTO recipe_locations (location_desc) VALUES ('Alkohol');
INSERT INTO recipe_locations (location_desc) VALUES ('Biologisch');
INSERT INTO recipe_locations (location_desc) VALUES ('Bohnen');
INSERT INTO recipe_locations (location_desc) VALUES ('Bonbon');
INSERT INTO recipe_locations (location_desc) VALUES ('Brot');
INSERT INTO recipe_locations (location_desc) VALUES ('Dosenfleisch &amp; Fisch');
INSERT INTO recipe_locations (location_desc) VALUES ('Dosengemüse');
INSERT INTO recipe_locations (location_desc) VALUES ('Erdnussbutter/Gelee/Honig');
INSERT INTO recipe_locations (location_desc) VALUES ('Erzeugen');
INSERT INTO recipe_locations (location_desc) VALUES ('Feinkostladen');
INSERT INTO recipe_locations (location_desc) VALUES ('Fleisch');
INSERT INTO recipe_locations (location_desc) VALUES ('Frei');
INSERT INTO recipe_locations (location_desc) VALUES ('Gebäck');
INSERT INTO recipe_locations (location_desc) VALUES ('Gesichtstuchpapier');
INSERT INTO recipe_locations (location_desc) VALUES ('Getränkemischung');
INSERT INTO recipe_locations (location_desc) VALUES ('Gewürze');
INSERT INTO recipe_locations (location_desc) VALUES ('Haushaltsreiniger');
INSERT INTO recipe_locations (location_desc) VALUES ('Heiße und kalte Getreide');
INSERT INTO recipe_locations (location_desc) VALUES ('Kaffee, Tea &amp; Kakao');
INSERT INTO recipe_locations (location_desc) VALUES ('Kandierte Frucht');
INSERT INTO recipe_locations (location_desc) VALUES ('Kekse');
INSERT INTO recipe_locations (location_desc) VALUES ('Kosher');
INSERT INTO recipe_locations (location_desc) VALUES ('Limo');
INSERT INTO recipe_locations (location_desc) VALUES ('Meeresfrüchte');
INSERT INTO recipe_locations (location_desc) VALUES ('Molkerei');
INSERT INTO recipe_locations (location_desc) VALUES ('Nudeln &amp; Soße');
INSERT INTO recipe_locations (location_desc) VALUES ('Öl/Essig/Dressing');
INSERT INTO recipe_locations (location_desc) VALUES ('Pfannkuchen &amp; Sirup');
INSERT INTO recipe_locations (location_desc) VALUES ('Plätzchen');
INSERT INTO recipe_locations (location_desc) VALUES ('Reis');
INSERT INTO recipe_locations (location_desc) VALUES ('Saft &amp; Cocktail');
INSERT INTO recipe_locations (location_desc) VALUES ('Salzige Snacks &amp; Chips');
INSERT INTO recipe_locations (location_desc) VALUES ('Seife');
INSERT INTO recipe_locations (location_desc) VALUES ('Speisekammer');
INSERT INTO recipe_locations (location_desc) VALUES ('Suppe');
INSERT INTO recipe_locations (location_desc) VALUES ('Tiefkühlkost');
INSERT INTO recipe_locations (location_desc) VALUES ('Toilettenpapier');
INSERT INTO recipe_locations (location_desc) VALUES ('Waschmittel');
INSERT INTO recipe_locations (location_desc) VALUES ('Würzmittel');

INSERT INTO recipe_bases (base_desc) VALUES ('Huhn');
INSERT INTO recipe_bases (base_desc) VALUES ('Pute');
INSERT INTO recipe_bases (base_desc) VALUES ('Rind');
INSERT INTO recipe_bases (base_desc) VALUES ('Schwein');
INSERT INTO recipe_bases (base_desc) VALUES ('Meeresfrüchte');
INSERT INTO recipe_bases (base_desc) VALUES ('Gemüse');
INSERT INTO recipe_bases (base_desc) VALUES ('Nudeln');
INSERT INTO recipe_bases (base_desc) VALUES ('Kartoffeln');
INSERT INTO recipe_bases (base_desc) VALUES ('Reis');
INSERT INTO recipe_bases (base_desc) VALUES ('Sonstiges');

INSERT INTO recipe_prep_time (time_desc) VALUES ('Lange');
INSERT INTO recipe_prep_time (time_desc) VALUES ('Mittel');
INSERT INTO recipe_prep_time (time_desc) VALUES ('Schnell');

INSERT INTO recipe_difficulty (difficult_desc) VALUES ('Leicht');
INSERT INTO recipe_difficulty (difficult_desc) VALUES ('Fortgeschritten');
INSERT INTO recipe_difficulty (difficult_desc) VALUES ('Schwierig');
INSERT INTO recipe_difficulty (difficult_desc) VALUES ('Experte');

INSERT INTO recipe_courses (course_desc) VALUES ('Frühstück');
INSERT INTO recipe_courses (course_desc) VALUES ('Snack');
INSERT INTO recipe_courses (course_desc) VALUES ('Mittagessen');
INSERT INTO recipe_courses (course_desc) VALUES ('Vorspeise');
INSERT INTO recipe_courses (course_desc) VALUES ('Beilage');
INSERT INTO recipe_courses (course_desc) VALUES ('Hauptgericht');
INSERT INTO recipe_courses (course_desc) VALUES ('Dessert');
INSERT INTO recipe_courses (course_desc) VALUES ('Getr&auml&auml;;nk');
INSERT INTO recipe_courses (course_desc) VALUES ('Salat');
